### ISSUE TITLE
impossible to plot only part of points ith the ggplotSampleMDS() function

### ISSUE THREAD

**Issue by OlivMC** [UCLouvain-CBIO/CytoMDS#1]
Dear,
I'm testing the package on a large dataset (700 files raw + 700 files corrected for batch effect, 40 individuals, 35 batch, 20 samples per batch, on 3 different tissues) and I'd really appreciate to be able to plot only a part of the files for correction efficiency analysis, depending the batch/tissue/individual/tissue, and I don't figure out how to perform this with the ggplotSampleMDS() function.
Could you please help me ?
Thanks a lot for you forthcoming help as well as for this super smart package !
Olivier

**Comment by phauchamps** [comment]
Hi @OlivMC, 
Thanks a lot for testing/using the CytoMDS package!
As a matter of fact you are right, in the current state it is not so easy to plot only a subset of samples from an already calculated MDS object. Adding this feature should not be too difficult, I should get back to you soon :-)

**Comment by phauchamps** [comment]
Hi @OlivMC, 
I added a sampleSubset argument in the `ggplotSampleMDS()` method to allow for easy selection of display points.
Could you possibly test this new version ?

**Comment by OlivMC** [comment]
Wonderfull ! It works well ! Just had to pay attension to the absence of the "s" in the function "ggplotSampleMDS" ;-)
Thanks a lot !

**Comment by phauchamps** [comment]
Yes I updated the name of the function in a previous version :-)
